/**
 * Single-file build (AC-7.1; frontend pre-flight CSP finding): emits ONE
 * self-contained dist/index.html with inlined minified JS + CSS under a
 * HASH-based CSP — 'self' sources are FORBIDDEN (they break on file://
 * opaque origins). Hashes are recomputed on every build.
 * Run: bun run build.ts
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { parse as parseYaml } from "yaml";

const ROOT = join(import.meta.dir, "..", "..");

// 1. Embed schemas + i18n as a generated module.
const core = JSON.parse(readFileSync(join(ROOT, "schema/rcp-core-v1.schema.json"), "utf8"));
const profiles: Record<string, unknown> = {};
for (const f of readdirSync(join(ROOT, "schema/profiles"))) {
  if (f.endsWith(".schema.json")) {
    profiles[f.replace(".schema.json", "")] = JSON.parse(
      readFileSync(join(ROOT, "schema/profiles", f), "utf8"),
    );
  }
}
const i18n = parseYaml(readFileSync(join(ROOT, "i18n/pt-PT.yaml"), "utf8"));
const example = readFileSync(join(import.meta.dir, "example.rcp.yaml"), "utf8");
// Registry display-name layer (id -> {pt, en}) — the registry's own
// localization, embedded so rendered ingredients/steps show real names.
const names: Record<string, unknown> = {};
for (const kind of ["ingredient", "primitive", "equipment", "technique"]) {
  const dir = join(ROOT, "registry/entries", kind);
  for (const f of readdirSync(dir)) {
    if (!f.endsWith(".yaml")) continue;
    const e = parseYaml(readFileSync(join(dir, f), "utf8"));
    if (e?.id && e?.display_name) names[e.id] = e.display_name;
  }
}
// Canonical links (SR-REG-001): a registry entry carrying
// canonical_recipe names a document that TEACHES it. Project the link
// AND the document it names, so the shipped bundle can actually resolve
// a mention — the engine declares the `links` capability only when this
// corpus is present, so without this projection see-the-method would
// pass every test and be unreachable in the browser.
const linkCorpus: Record<string, { label: string; document: unknown }> = {};
const documentsById: Record<string, unknown> = {};
for (const dir of [join(ROOT, "examples"), join(ROOT, "examples/boston-1910")]) {
  for (const f of readdirSync(dir)) {
    if (!f.endsWith(".rcp.yaml")) continue;
    const raw = readFileSync(join(dir, f), "utf8");
    for (const chunk of raw.split(/^---$/m)) {
      if (!chunk.trim()) continue;
      const d = parseYaml(chunk);
      if (d?.id) documentsById[d.id] = d;
    }
  }
}
for (const kind of ["technique", "ingredient"]) {
  const dir = join(ROOT, "registry/entries", kind);
  for (const f of readdirSync(dir)) {
    if (!f.endsWith(".yaml")) continue;
    const e = parseYaml(readFileSync(join(dir, f), "utf8"));
    const link = e?.canonical_recipe;
    if (!e?.id || !link?.id) continue;
    const target = documentsById[link.id];
    if (!target) continue; // an unresolvable link is simply not offered
    const dn = e.display_name ?? {};
    linkCorpus[e.id] = { label: dn.pt ?? dn.en ?? e.id, document: target };
  }
}

writeFileSync(
  join(import.meta.dir, "src/generated/embedded.ts"),
  `// GENERATED by build.ts — do not edit.\n` +
    `export const EMBEDDED_LINKS = ${JSON.stringify(linkCorpus)};\n` +
    `export const EMBEDDED_SCHEMAS = ${JSON.stringify({ core, profiles })} as never;\n` +
    `export const EMBEDDED_I18N = ${JSON.stringify({ taxonomy: i18n.taxonomy, tags: i18n.tags })};\n` +
    `export const EMBEDDED_EXAMPLE = ${JSON.stringify(example)};\n` +
    `export const EMBEDDED_NAMES = ${JSON.stringify(names)};\n`,
);

// 2. Bundle + minify.
const result = await Bun.build({
  entrypoints: [join(import.meta.dir, "src/main.ts")],
  minify: true,
  target: "browser",
});
if (!result.success) {
  console.error(result.logs.join("\n"));
  process.exit(1);
}
const js = await result.outputs[0]!.text();
const css = readFileSync(join(import.meta.dir, "style.css"), "utf8");

// 3. Hash-based CSP (never 'self').
const hash = (s: string) =>
  "sha256-" + Buffer.from(new Bun.CryptoHasher("sha256").update(s).digest()).toString("base64");
const csp = [
  "default-src 'none'",
  `script-src '${hash(js)}'`,
  `style-src '${hash(css)}'`,
  "img-src data: blob:",
  "media-src data: blob:",
].join("; ");

// 4. Single-file page. charset FIRST; semantic structure; aria-live verdicts.
const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="${csp}">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>RCP viewer</title>
<style>${css}</style>
</head>
<body>
<main>
<h1>RCP viewer</h1>
<p>Valide e leia um documento RCP — tudo corre localmente, nada é enviado. A caixa aceita colar (teclado) ou arrastar o ficheiro.</p>
<label for="input">Documento .rcp.yaml ou JSON</label>
<div class="toolbar"><button id="load-example" type="button">Carregar exemplo (torta de três camadas)</button>\n<label class="file-label" for="file-input">Ficheiros (documento e/ou media)</label>\n<input id="file-input" type="file" multiple></div>
<textarea id="input" spellcheck="false" autocomplete="off"></textarea>
<p id="busy" hidden>a validar…</p>
<div id="verdicts" aria-live="polite"></div>
<div id="render"></div>
</main>
<script>${js}</script>
</body>
</html>
`;
mkdirSync(join(import.meta.dir, "dist"), { recursive: true });
writeFileSync(join(import.meta.dir, "dist/index.html"), html);
console.log(`dist/index.html: ${(html.length / 1024).toFixed(1)} KiB, CSP hashes embedded`);
