/** Build the offline, single-file Schemami viewer. */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..", "..");
const schema = JSON.parse(
  readFileSync(join(ROOT, "schema", "schemami-v1-core.schema.json"), "utf8"),
);
const example = readFileSync(
  join(ROOT, "examples", "pao-massa-mae.schemami.yaml"),
  "utf8",
);
const unitLabels = {
  g: "g",
  kg: "kg",
  mL: "mL",
  L: "L",
  Cel: "°C",
  "[degF]": "°F",
  "[cup_us]": "cup (US)",
  "[tbs_us]": "tbsp (US)",
  "[tsp_us]": "tsp (US)",
  "[foz_us]": "fl oz (US)",
  "[cup_m]": "cup (240 mL)",
};

writeFileSync(
  join(import.meta.dir, "src", "schemami", "generated.ts"),
  `// GENERATED by tools/viewer/build.ts — do not edit.\n` +
    `export const EMBEDDED_SCHEMA = ${JSON.stringify(schema)} as Record<string, unknown>;\n` +
    `export const EMBEDDED_EXAMPLE = ${JSON.stringify(example)};\n` +
    `export const EMBEDDED_UNIT_LABELS = ${JSON.stringify(unitLabels)} as Record<string, string>;\n`,
);

const result = await Bun.build({
  entrypoints: [join(import.meta.dir, "src", "schemami", "main.ts")],
  minify: true,
  target: "browser",
});
if (!result.success) {
  console.error(result.logs.join("\n"));
  process.exit(1);
}
const js = await result.outputs[0]!.text();
const css = readFileSync(join(import.meta.dir, "style.css"), "utf8");
const hash = (source: string) =>
  "sha256-" + Buffer.from(new Bun.CryptoHasher("sha256").update(source).digest()).toString("base64");
const csp = [
  "default-src 'none'",
  `script-src '${hash(js)}'`,
  `style-src '${hash(css)}'`,
].join("; ");

const html = `<!doctype html>
<html lang="pt-PT">
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="${csp}">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Schemami viewer</title>
<style>${css}</style>
</head>
<body>
<main>
<h1>Schemami viewer</h1>
<p>Valide, leia e calcule uma receita Schemami localmente. Nenhum conteúdo é enviado.</p>
<label for="input">Documento .schemami.yaml ou .schemami.json</label>
<div class="toolbar">
  <button id="load-example" type="button">Carregar exemplo</button>
  <label class="file-label" for="file-input">Abrir documento</label>
  <input id="file-input" type="file" accept=".yaml,.json,.schemami.yaml,.schemami.json">
</div>
<textarea id="input" spellcheck="false" autocomplete="off"></textarea>
<p id="busy" hidden>a validar…</p>
<div id="verdicts" aria-live="polite"></div>
<div id="render"></div>
</main>
<script>${js}</script>
</body>
</html>
`;
mkdirSync(join(import.meta.dir, "dist"), { recursive: true });
writeFileSync(join(import.meta.dir, "dist", "index.html"), html);
console.log(`dist/index.html: ${(html.length / 1024).toFixed(1)} KiB, CSP hashes embedded`);
