import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dir, "..");
const schema = JSON.parse(readFileSync(join(root, "resources", "schema", "schemami-v1-core.schema.json"), "utf8"));
const bundle = JSON.parse(readFileSync(join(root, "resources", "schema", "schemami-v1-bundle.schema.json"), "utf8"));
const embeddedCoreDefinitions = JSON.parse(JSON.stringify(schema.$defs).replaceAll(
  "#/$defs/",
  "#/$defs/core/",
));
bundle.$defs = { core: embeddedCoreDefinitions };
const bundledSchema = JSON.parse(JSON.stringify(bundle).replaceAll(
  "https://schemami.dev/schema/schemami/1/core.schema.json#/$defs/",
  "#/$defs/core/",
));
writeFileSync(
  join(root, "src", "generated.ts"),
  `// GENERATED by sdk/typescript/scripts/sync-resources.ts — do not edit.\n` +
  `export const EMBEDDED_SCHEMA = ${JSON.stringify(schema)} as Record<string, unknown>;\n` +
  `export const EMBEDDED_BUNDLE_SCHEMA = ${JSON.stringify(bundledSchema)} as Record<string, unknown>;\n`,
);
