import { isAdmittedRecipe, type AdmittedRecipe, type JSONValue, type JSONObject } from "./core.ts";

export type ChangeKind = "added" | "removed" | "renamed" | "modified" | "reordered";
export type DocumentIdentity = { collection:string; id:string; revision:number; sha256:string };
export type ProtocolChange = { kind:ChangeKind; pointer:string; sourcePointer?:string; candidatePointer?:string; sourceValue?:JSONValue; candidateValue?:JSONValue };
export type ComparisonResult = { source:DocumentIdentity; candidate:DocumentIdentity; changes:ProtocolChange[]; hasChanges:boolean };

export function compare(source:AdmittedRecipe,candidate:AdmittedRecipe):ComparisonResult { if(!isAdmittedRecipe(source)||!isAdmittedRecipe(candidate))throw new TypeError("SchemamiDiff requires admitted recipes");const changes:ProtocolChange[]=[];compareValues(source.value,candidate.value,"","",changes);const order:Record<ChangeKind,number>={removed:0,added:1,renamed:2,modified:3,reordered:4};changes.sort((a,b)=>ascii(a.pointer,b.pointer)||order[a.kind]-order[b.kind]||ascii(String(a.sourcePointer??""),String(b.sourcePointer??"")));return{source:identity(source),candidate:identity(candidate),changes,hasChanges:changes.length>0}; }
function compareValues(source:JSONValue,candidate:JSONValue,sp:string,cp:string,out:ProtocolChange[]):void {if(equal(source,candidate))return;if(object(source)&&object(candidate)){const keys=[...new Set([...Object.keys(source),...Object.keys(candidate)])].sort();for(const key of keys){const hs=Object.hasOwn(source,key),hc=Object.hasOwn(candidate,key),s=pointer(sp,key),c=pointer(cp,key);if(!hs)out.push(change("added",undefined,c,undefined,candidate[key]));else if(!hc)out.push(change("removed",s,undefined,source[key],undefined));else compareValues(source[key],candidate[key],s,c,out);}return;}if(Array.isArray(source)&&Array.isArray(candidate)){const sourceIds=identified(source),candidateIds=identified(candidate);if(sourceIds&&candidateIds){compareIdentified(source,candidate,sourceIds,candidateIds,sp,cp,out);return;}if(sameMultiset(source,candidate)){out.push(change("reordered",sp,cp,source,candidate));return;}const common=Math.min(source.length,candidate.length);for(let i=0;i<common;i+=1)compareValues(source[i],candidate[i],pointer(sp,String(i)),pointer(cp,String(i)),out);for(let i=common;i<source.length;i+=1)out.push(change("removed",pointer(sp,String(i)),undefined,source[i],undefined));for(let i=common;i<candidate.length;i+=1)out.push(change("added",undefined,pointer(cp,String(i)),undefined,candidate[i]));return;}out.push(change(cp.endsWith("/name")?"renamed":"modified",sp,cp,source,candidate));}
function identified(values:JSONValue[]):string[]|null{const ids:string[]=[];const seen=new Set<string>();for(const value of values){if(!object(value)||typeof value.id!=="string"||seen.has(value.id))return null;seen.add(value.id);ids.push(value.id);}return ids;}
function compareIdentified(source:JSONValue[],candidate:JSONValue[],sourceIds:string[],candidateIds:string[],sp:string,cp:string,out:ProtocolChange[]):void{const si=new Map(sourceIds.map((id,index)=>[id,index])),ci=new Map(candidateIds.map((id,index)=>[id,index]));for(const id of [...new Set([...sourceIds,...candidateIds])].sort()){const left=si.get(id),right=ci.get(id);if(left===undefined)out.push(change("added",undefined,pointer(cp,String(right)),undefined,candidate[right!]));else if(right===undefined)out.push(change("removed",pointer(sp,String(left)),undefined,source[left],undefined));else compareValues(source[left],candidate[right],pointer(sp,String(left)),pointer(cp,String(right)),out);}const common=new Set(sourceIds.filter((id)=>ci.has(id)));const leftOrder=sourceIds.filter((id)=>common.has(id)),rightOrder=candidateIds.filter((id)=>common.has(id));if(!equal(leftOrder,rightOrder))out.push(change("reordered",sp,cp,leftOrder,rightOrder));}
function change(kind:ChangeKind,sp:string|undefined,cp:string|undefined,sv:JSONValue|undefined,cv:JSONValue|undefined):ProtocolChange{return{kind,pointer:cp??sp??"",...(sp===undefined?{}:{sourcePointer:sp}),...(cp===undefined?{}:{candidatePointer:cp}),...(sv===undefined?{}:{sourceValue:sv}),...(cv===undefined?{}:{candidateValue:cv})};}
function object(value:JSONValue):value is JSONObject{return value!==null&&typeof value==="object"&&!Array.isArray(value);}
function equal(a:JSONValue,b:JSONValue):boolean{
  if(a===b)return true;
  if(Array.isArray(a)&&Array.isArray(b))return a.length===b.length&&a.every((value,index)=>equal(value,b[index]));
  if(object(a)&&object(b)){const left=Object.keys(a).sort(),right=Object.keys(b).sort();return left.length===right.length&&left.every((key,index)=>key===right[index]&&equal(a[key],b[key]));}
  return false;
}
function sameMultiset(a:JSONValue[],b:JSONValue[]):boolean{if(a.length!==b.length||equal(a,b))return false;const remaining=[...b];for(const item of a){const index=remaining.findIndex((candidate)=>equal(item,candidate));if(index<0)return false;remaining.splice(index,1);}return true;}
function pointer(base:string,token:string):string{return `${base}/${token.replaceAll("~","~0").replaceAll("/","~1")}`;}
function identity(document:AdmittedRecipe):DocumentIdentity{const value=document.value;return{collection:String(value.collection),id:String(value.id),revision:Number(value.revision),sha256:document.sha256};}
function ascii(left:string,right:string):number{return left<right?-1:left>right?1:0;}
