import { expect,test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { AdmittedRecipe,admit,canonicalJSON,parse } from "../src/index.ts";
import { compare } from "../src/diff.ts";

test("Diff reports a title modification without mutating source",async()=>{const raw=readFileSync(join(import.meta.dir,"..","testdata","phase9-minimal.schemami.json"));const first=parse(raw);if(first.status!=="parsed")throw new Error("parse");const source=await admit(first.parsed);if(source.status!=="recipe")throw new Error("admit");const changed=source.recipe.value;changed.title="Candidate title";const second=parse(canonicalJSON(changed));if(second.status!=="parsed")throw new Error("parse candidate");const candidate=await admit(second.parsed);if(candidate.status!=="recipe")throw new Error("admit candidate");const result=compare(source.recipe,candidate.recipe);expect(result.changes).toHaveLength(1);expect(result.changes[0]).toMatchObject({kind:"modified",pointer:"/title"});expect(source.recipe.value.title).not.toBe("Candidate title");});

test("Diff follows local IDs through an authored reorder",async()=>{const base={schemami:"1",collection:"test",id:"order",revision:1,content_language:"pt-PT",title:"Order",ingredients:[{id:"a",name:"A"},{id:"b",name:"B"}],method:{sequence:[]}};const first=parse(JSON.stringify(base));const second=parse(JSON.stringify({...base,revision:2,ingredients:[base.ingredients[1],base.ingredients[0]]}));if(first.status!=="parsed"||second.status!=="parsed")throw new Error("parse");const source=await admit(first.parsed),candidate=await admit(second.parsed);if(source.status!=="recipe"||candidate.status!=="recipe")throw new Error("admit");const result=compare(source.recipe,candidate.recipe);expect(result.changes).toContainEqual(expect.objectContaining({kind:"reordered",pointer:"/ingredients"}));expect(result.changes.some((item)=>item.pointer==="/ingredients/0/id"||item.pointer==="/ingredients/1/id")).toBe(false);});

test("Diff ignores object member order when detecting extension-array reorder",async()=>{const base={schemami:"1",collection:"test",id:"extensions",revision:1,content_language:"pt-PT",title:"Extensions",ingredients:[],method:{sequence:[]},"x-values":[{a:1,b:2},{c:3,d:4}]};const candidate={...base,revision:2,"x-values":[{d:4,c:3},{b:2,a:1}]};const first=parse(JSON.stringify(base)),second=parse(JSON.stringify(candidate));if(first.status!=="parsed"||second.status!=="parsed")throw new Error("parse");const source=await admit(first.parsed),target=await admit(second.parsed);if(source.status!=="recipe"||target.status!=="recipe")throw new Error("admit");const result=compare(source.recipe,target.recipe);expect(result.changes).toContainEqual(expect.objectContaining({kind:"reordered",pointer:"/x-values"}));expect(result.changes.filter((item)=>item.pointer.startsWith("/x-values/")).length).toBe(0);});

test("Diff matches the shared cross-language conformance corpus",async()=>{
 const corpus=JSON.parse(readFileSync(join(import.meta.dir,"..","resources","conformance","diff.json"),"utf8")) as {vectors:Array<{id:string;source:Record<string,unknown>;candidate:Record<string,unknown>;expected_changes:Array<Record<string,string>>}>};
 for(const vector of corpus.vectors){const sourceParsed=parse(JSON.stringify(vector.source)),candidateParsed=parse(JSON.stringify(vector.candidate));if(sourceParsed.status!=="parsed"||candidateParsed.status!=="parsed")throw new Error(`${vector.id}: parse`);const source=await admit(sourceParsed.parsed),candidate=await admit(candidateParsed.parsed);if(source.status!=="recipe"||candidate.status!=="recipe")throw new Error(`${vector.id}: admit`);const actual=compare(source.recipe,candidate.recipe).changes.map((change)=>({kind:change.kind,pointer:change.pointer,...(change.sourcePointer===undefined?{}:{source_pointer:change.sourcePointer}),...(change.candidatePointer===undefined?{}:{candidate_pointer:change.candidatePointer})}));expect(actual,vector.id).toEqual(vector.expected_changes);}
});

test("Diff refuses forged admission handles",()=>{const fake=Object.create(AdmittedRecipe.prototype);Object.defineProperties(fake,{value:{value:{}},sha256:{value:"forged"}});expect(()=>compare(fake,fake)).toThrow();});
